tests/Makefile.am: Include t_common.h for make distcheck
With a distcheck build, t_common.h wasn't being copied over to
the build dir, so it couldn't be found causing:

    ../../../tests/t_common.c:4:10: fatal error: t_common.h: No such file or directory
        4 | #include <t_common.h>
          |          ^~~~~~~~~~~~
    compilation terminated.
    make[3]: *** [Makefile:525: t_common.o] Error 1
    make[3]: Leaving directory '/srv/cyrus-sasl/cyrus-sasl-2.1.28/_build/sub/tests'
    make[2]: *** [Makefile:691: all-recursive] Error 1
    make[2]: Leaving directory '/srv/cyrus-sasl/cyrus-sasl-2.1.28/_build/sub'
    make[1]: *** [Makefile:559: all] Error 2
    make[1]: Leaving directory '/srv/cyrus-sasl/cyrus-sasl-2.1.28/_build/sub'
    make: *** [Makefile:910: distcheck] Error 1